### PR TITLE
Added composer config

### PR DESCRIPTION
**Pull request by toby-griffiths**
Hi there,

I was hoping to use your library in a composer project, so I've added the composer.json & composer.lock files to my fork, with your details.

Rather than publish this myself I thought it better to send you a pull request so that you could add it to packagist yourself.

Thanks for the great library

### CODE REVIEW

**Comment by ernix** [comment]
Thank you, merged.

**Comment by toby-griffiths** [comment]
@ernix Awesome.  Do you want to submit it to Packagist.org, or shall I?

**Comment by ernix** [comment]
@toby-griffiths Sorry for the late reply.  I submitted it to Packagist.org.
https://packagist.org/packages/ernix/lettercase

I fully appreciate your cooperation too.

**Comment by toby-griffiths** [comment]
Awesome.  Just glad to help :)

**Pull request merged**
